### ISSUE TITLE
Download URL Scraping is Broken

### ISSUE THREAD

**Issue by jmsmdy** [JessicaTegner/PyTinyTeX#1]
```
>>> pytinytex.download_tinytex()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/envs/pandoc/lib/python3.9/site-packages/pytinytex/tinytex_download.py", line 24, in download_tinytex
    tinytex_urls, _ = _get_tinytex_urls(version, variation)
  File "/opt/anaconda3/envs/pandoc/lib/python3.9/site-packages/pytinytex/tinytex_download.py", line 80, in _get_tinytex_urls
    version = tinytex_urls_list[0].split('/')[5]
IndexError: list index out of range
```

**Comment by JessicaTegner** [comment]
ohh yes @jmsmdy 
It's broken because of the recent change in how GitHub populate theirs release page. I'll write a fix for it within the next couple of days
